kind: Service
apiVersion: v1
metadata:
  name: timems
  labels:
    app: time-ms
spec:
  selector:
    app: time-ms
  ports:
  - protocol: TCP
    port: 81
    targetPort: 3001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timems
  labels:
    app: time-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-ms
  template:
    metadata:
      labels:
        app: time-ms
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "timems"
        dapr.io/app-port: "3001"
        dapr.io/config: tracing
    spec:
      containers:
      - name: nodems
        image: acrparveenkumar.azurecr.io/timemsnodejs:latest
        ports:
        - containerPort: 3001
        imagePullPolicy: Always
